// Code generated by "linkname-gen -symbol github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).goTag -def func goTag(*generator.Generator, *generator.Descriptor, *descriptor.FieldDescriptorProto, string) string"; DO NOT EDIT.

package protostruct

import (
	_ "unsafe"

	"github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	"github.com/gogo/protobuf/protoc-gen-gogo/generator"
)

//go:linkname goTag github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).goTag
func goTag(*generator.Generator, *generator.Descriptor, *descriptor.FieldDescriptorProto, string) string
