sudo: required

services:
    - memcached
    - redis-server
    - cassandra

language: go
go:
    - 1.8
    - 1.8.1
    - 1.8.3
    - 1.9
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get -u github.com/mattn/goveralls
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/Masterminds/glide
    #- go get -u github.com/znly/linkname-gen
install:
    - glide update -v --force
    #- go generate . ./protoscan
script:
    ## Note that we MUST specify an output path for the test binary, otherwise
    ## Go 1.9+ will silently strip the symbols during test execution, and break
    ## everything in the process.
    ## This affects only `go test`, not `go build`, and only on Linux.
    - go test -v -race -cpu 1,2,4 -run=. -bench=. -covermode=atomic -coverprofile=coverage1.out -o protein1.test .
    - go test -v -race -cpu 1,2,4 -run=. -bench=. -covermode=atomic -coverprofile=coverage2.out -o protein2.test ./protoscan
    - bash coverage.sh
