os:
    - linux
services:
    - memcached
    - redis-server
    - cassandra
sudo: required

language: go
go:
    - 1.8.4
    - 1.9.1
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - make -f Makefile.ci deps_external
    - make -f Makefile.ci tools_external
install:
    - make -f Makefile deps
script:
    - make -f Makefile.ci tests
    - make -f Makefile.ci coverage
