sudo: required

services:
    - memcached
    - redis-server
    - cassandra

language: go
go:
    - 1.8
    - 1.8.1
    - 1.8.3
    - 1.9
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get -u github.com/mattn/goveralls
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/Masterminds/glide
    - go get -u github.com/znly/linkname-gen
install:
    - go get -u github.com/znly/protein/... || true
    - glide update -v --force
    - go generate . ./protoscan
script:
    - go test -v -race -cpu 1,2,4 -run=. -bench=. -covermode=atomic -coverprofile=coverage1.out .
    - go test -v -race -cpu 1,2,4 -run=. -bench=. -covermode=atomic -coverprofile=coverage2.out ./protoscan
    - bash coverage.sh
