os:
    - linux
services:
    - memcached
    - redis-server
    - cassandra
sudo: required

language: go
go:
    - "1.8.7"
    - "1.9.4"
    - "1.10"
env:
    - PATH=/home/travis/gopath/bin:$PATH
      PROT_CQL_ADDRS=localhost:9042
      PROT_REDIS_URI=redis://localhost:6379/0
      PROT_MEMCACHED_ADDRS=localhost:11211
before_install:
    - make -f Makefile.ci deps_external
    - make -f Makefile.ci tools_external
install:
    - make -f Makefile deps
script:
    - make -f Makefile.ci tests
    - make -f Makefile.ci coverage
