// Code generated by "linkname-gen -symbol github.com/gogo/protobuf/proto.(*Buffer).unmarshalType -def func unmarshalType(*proto.Buffer, reflect.Type, *proto.StructProperties, bool, unsafe.Pointer) error"; DO NOT EDIT.

package protein

import (
	"reflect"
	"unsafe"
	_ "unsafe"

	"github.com/gogo/protobuf/proto"
)

// This avoids some weird goimports issues that I've been facing on linux/amd64
// since Go1.9+.
var (
	_ *proto.Buffer
	_ reflect.Type
	_ *proto.StructProperties
	_ unsafe.Pointer
)

//go:linkname unmarshalType github.com/gogo/protobuf/proto.(*Buffer).unmarshalType
func unmarshalType(*proto.Buffer, reflect.Type, *proto.StructProperties, bool, unsafe.Pointer) error
