// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/znly/protein/protobuf/protobuf_payload.proto

/*
Package protein is a generated protocol buffer package.

It is generated from these files:
	github.com/znly/protein/protobuf/protobuf_payload.proto
	github.com/znly/protein/protobuf/protobuf_schema.proto

It has these top-level messages:
	ProtobufPayload
	ProtobufSchema
*/
package protein

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// ProtobufPayload is a protobuf payload annotated with the unique versioning
// identifier of its schema.
//
// This allows a `ProtobufPayload` to be decoded at runtime using Protein's
// `Transcoder`.
//
// See `ScanSchemas`'s documentation for more information.
type ProtobufPayload struct {
	// SchemaUID is the unique, deterministic & versioned identifier of the
	// `payload`'s schema.
	SchemaUID string `protobuf:"bytes,1,opt,name=schema_uid,json=schemaUid,proto3" json:"schema_uid,omitempty"`
	// Payload is the actual, marshaled protobuf payload.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ProtobufPayload) Reset()                    { *m = ProtobufPayload{} }
func (m *ProtobufPayload) String() string            { return proto.CompactTextString(m) }
func (*ProtobufPayload) ProtoMessage()               {}
func (*ProtobufPayload) Descriptor() ([]byte, []int) { return fileDescriptorProtobufPayload, []int{0} }

func (m *ProtobufPayload) GetSchemaUID() string {
	if m != nil {
		return m.SchemaUID
	}
	return ""
}

func (m *ProtobufPayload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtobufPayload)(nil), "protein.ProtobufPayload")
}
func (this *ProtobufPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protein.ProtobufPayload{")
	s = append(s, "SchemaUID: "+fmt.Sprintf("%#v", this.SchemaUID)+",\n")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringProtobufPayload(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

func init() {
	proto.RegisterFile("github.com/znly/protein/protobuf/protobuf_payload.proto", fileDescriptorProtobufPayload)
}

var fileDescriptorProtobufPayload = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xaf, 0xca, 0xcb, 0xa9, 0xd4, 0x2f, 0x28, 0xca, 0x2f,
	0x49, 0xcd, 0xcc, 0x03, 0xd3, 0xf9, 0x49, 0xa5, 0x69, 0x70, 0x46, 0x7c, 0x41, 0x62, 0x65, 0x4e,
	0x7e, 0x62, 0x8a, 0x1e, 0x58, 0x40, 0x88, 0x1d, 0xaa, 0x50, 0x4a, 0x16, 0xae, 0x32, 0x3d, 0x3f,
	0x3d, 0x1f, 0xcc, 0x01, 0xb3, 0x20, 0xea, 0x94, 0xd2, 0xb8, 0xf8, 0x03, 0xa0, 0x0a, 0x02, 0x20,
	0x06, 0x08, 0xe9, 0x70, 0x71, 0x15, 0x27, 0x67, 0xa4, 0xe6, 0x26, 0xc6, 0x97, 0x66, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x3a, 0xf1, 0x3e, 0xba, 0x27, 0xcf, 0x19, 0x0c, 0x16, 0x0d, 0xf5,
	0x74, 0x09, 0xe2, 0x84, 0x28, 0x08, 0xcd, 0x4c, 0x11, 0x52, 0xe5, 0x62, 0x87, 0xda, 0x2c, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0xe3, 0xc4, 0xfd, 0xe8, 0x9e, 0x3c, 0x3b, 0xd4, 0xac, 0x20, 0x98, 0x9c,
	0x93, 0xc1, 0x87, 0x87, 0x72, 0x8c, 0x0d, 0x8f, 0xe4, 0x18, 0x3a, 0x1e, 0xc9, 0x31, 0x9c, 0x78,
	0x24, 0xc7, 0x70, 0xe1, 0x91, 0x1c, 0xc3, 0x8d, 0x47, 0x72, 0x0c, 0x0f, 0x1e, 0xc9, 0x31, 0xfc,
	0x78, 0x24, 0xc7, 0xd0, 0xf0, 0x58, 0x8e, 0x61, 0xc2, 0x63, 0x39, 0x86, 0x05, 0x8f, 0xe5, 0x18,
	0x36, 0x3c, 0x96, 0x63, 0x4c, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0x17, 0x4b, 0x23, 0x03, 0x01, 0x00, 0x00,
}
