// Code generated by protoc-gen-gogo.
// source: test_schema_xxx.proto
// DO NOT EDIT!

package protein

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OtherTestSchemaXXX struct {
	Ts *google_protobuf1.Timestamp `protobuf:"bytes,1,opt,name=ts" json:"ts,omitempty"`
}

func (m *OtherTestSchemaXXX) Reset()                    { *m = OtherTestSchemaXXX{} }
func (m *OtherTestSchemaXXX) String() string            { return proto.CompactTextString(m) }
func (*OtherTestSchemaXXX) ProtoMessage()               {}
func (*OtherTestSchemaXXX) Descriptor() ([]byte, []int) { return fileDescriptorTestSchemaXxx, []int{0} }

func (m *OtherTestSchemaXXX) GetTs() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type TestSchemaXXX struct {
	Uid    string                                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FqName string                                 `protobuf:"bytes,2,opt,name=fq_name,json=fqName,proto3" json:"fq_name,omitempty"`
	Deps   map[string]*TestSchemaXXX_NestedSchema `protobuf:"bytes,4,rep,name=deps" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Descr:
	//	*TestSchemaXXX_Str
	//	*TestSchemaXXX_Buf
	Descr isTestSchemaXXX_Descr         `protobuf_oneof:"descr"`
	Ts    *google_protobuf1.Timestamp   `protobuf:"bytes,7,opt,name=ts" json:"ts,omitempty"`
	Ots   *OtherTestSchemaXXX           `protobuf:"bytes,9,opt,name=ots" json:"ots,omitempty"`
	Nss   []*TestSchemaXXX_NestedSchema `protobuf:"bytes,8,rep,name=nss" json:"nss,omitempty"`
}

func (m *TestSchemaXXX) Reset()                    { *m = TestSchemaXXX{} }
func (m *TestSchemaXXX) String() string            { return proto.CompactTextString(m) }
func (*TestSchemaXXX) ProtoMessage()               {}
func (*TestSchemaXXX) Descriptor() ([]byte, []int) { return fileDescriptorTestSchemaXxx, []int{1} }

type isTestSchemaXXX_Descr interface {
	isTestSchemaXXX_Descr()
}

type TestSchemaXXX_Str struct {
	Str string `protobuf:"bytes,30,opt,name=str,proto3,oneof"`
}
type TestSchemaXXX_Buf struct {
	Buf []byte `protobuf:"bytes,31,opt,name=buf,proto3,oneof"`
}

func (*TestSchemaXXX_Str) isTestSchemaXXX_Descr() {}
func (*TestSchemaXXX_Buf) isTestSchemaXXX_Descr() {}

func (m *TestSchemaXXX) GetDescr() isTestSchemaXXX_Descr {
	if m != nil {
		return m.Descr
	}
	return nil
}

func (m *TestSchemaXXX) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TestSchemaXXX) GetFqName() string {
	if m != nil {
		return m.FqName
	}
	return ""
}

func (m *TestSchemaXXX) GetDeps() map[string]*TestSchemaXXX_NestedSchema {
	if m != nil {
		return m.Deps
	}
	return nil
}

func (m *TestSchemaXXX) GetStr() string {
	if x, ok := m.GetDescr().(*TestSchemaXXX_Str); ok {
		return x.Str
	}
	return ""
}

func (m *TestSchemaXXX) GetBuf() []byte {
	if x, ok := m.GetDescr().(*TestSchemaXXX_Buf); ok {
		return x.Buf
	}
	return nil
}

func (m *TestSchemaXXX) GetTs() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *TestSchemaXXX) GetOts() *OtherTestSchemaXXX {
	if m != nil {
		return m.Ots
	}
	return nil
}

func (m *TestSchemaXXX) GetNss() []*TestSchemaXXX_NestedSchema {
	if m != nil {
		return m.Nss
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TestSchemaXXX) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TestSchemaXXX_OneofMarshaler, _TestSchemaXXX_OneofUnmarshaler, _TestSchemaXXX_OneofSizer, []interface{}{
		(*TestSchemaXXX_Str)(nil),
		(*TestSchemaXXX_Buf)(nil),
	}
}

func _TestSchemaXXX_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TestSchemaXXX)
	// descr
	switch x := m.Descr.(type) {
	case *TestSchemaXXX_Str:
		_ = b.EncodeVarint(30<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Str)
	case *TestSchemaXXX_Buf:
		_ = b.EncodeVarint(31<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Buf)
	case nil:
	default:
		return fmt.Errorf("TestSchemaXXX.Descr has unexpected type %T", x)
	}
	return nil
}

func _TestSchemaXXX_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TestSchemaXXX)
	switch tag {
	case 30: // descr.str
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Descr = &TestSchemaXXX_Str{x}
		return true, err
	case 31: // descr.buf
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Descr = &TestSchemaXXX_Buf{x}
		return true, err
	default:
		return false, nil
	}
}

func _TestSchemaXXX_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TestSchemaXXX)
	// descr
	switch x := m.Descr.(type) {
	case *TestSchemaXXX_Str:
		n += proto.SizeVarint(30<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Str)))
		n += len(x.Str)
	case *TestSchemaXXX_Buf:
		n += proto.SizeVarint(31<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Buf)))
		n += len(x.Buf)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TestSchemaXXX_NestedSchema struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *TestSchemaXXX_NestedSchema) Reset()         { *m = TestSchemaXXX_NestedSchema{} }
func (m *TestSchemaXXX_NestedSchema) String() string { return proto.CompactTextString(m) }
func (*TestSchemaXXX_NestedSchema) ProtoMessage()    {}
func (*TestSchemaXXX_NestedSchema) Descriptor() ([]byte, []int) {
	return fileDescriptorTestSchemaXxx, []int{1, 0}
}

func (m *TestSchemaXXX_NestedSchema) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TestSchemaXXX_NestedSchema) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*OtherTestSchemaXXX)(nil), "protein.OtherTestSchemaXXX")
	proto.RegisterType((*TestSchemaXXX)(nil), "protein.TestSchemaXXX")
	proto.RegisterType((*TestSchemaXXX_NestedSchema)(nil), "protein.TestSchemaXXX.NestedSchema")
}
func (this *OtherTestSchemaXXX) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protein.OtherTestSchemaXXX{")
	if this.Ts != nil {
		s = append(s, "Ts: "+fmt.Sprintf("%#v", this.Ts)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TestSchemaXXX) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&protein.TestSchemaXXX{")
	s = append(s, "Uid: "+fmt.Sprintf("%#v", this.Uid)+",\n")
	s = append(s, "FqName: "+fmt.Sprintf("%#v", this.FqName)+",\n")
	keysForDeps := make([]string, 0, len(this.Deps))
	for k, _ := range this.Deps {
		keysForDeps = append(keysForDeps, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDeps)
	mapStringForDeps := "map[string]*TestSchemaXXX_NestedSchema{"
	for _, k := range keysForDeps {
		mapStringForDeps += fmt.Sprintf("%#v: %#v,", k, this.Deps[k])
	}
	mapStringForDeps += "}"
	if this.Deps != nil {
		s = append(s, "Deps: "+mapStringForDeps+",\n")
	}
	if this.Descr != nil {
		s = append(s, "Descr: "+fmt.Sprintf("%#v", this.Descr)+",\n")
	}
	if this.Ts != nil {
		s = append(s, "Ts: "+fmt.Sprintf("%#v", this.Ts)+",\n")
	}
	if this.Ots != nil {
		s = append(s, "Ots: "+fmt.Sprintf("%#v", this.Ots)+",\n")
	}
	if this.Nss != nil {
		s = append(s, "Nss: "+fmt.Sprintf("%#v", this.Nss)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TestSchemaXXX_Str) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&protein.TestSchemaXXX_Str{` +
		`Str:` + fmt.Sprintf("%#v", this.Str) + `}`}, ", ")
	return s
}
func (this *TestSchemaXXX_Buf) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&protein.TestSchemaXXX_Buf{` +
		`Buf:` + fmt.Sprintf("%#v", this.Buf) + `}`}, ", ")
	return s
}
func (this *TestSchemaXXX_NestedSchema) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protein.TestSchemaXXX_NestedSchema{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTestSchemaXxx(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

func init() { proto.RegisterFile("test_schema_xxx.proto", fileDescriptorTestSchemaXxx) }

var fileDescriptorTestSchemaXxx = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x50, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0x9d, 0x24, 0xdf, 0xd7, 0xd8, 0x69, 0x05, 0x19, 0x14, 0x43, 0xc4, 0x69, 0xa8, 0x9b, 0x22,
	0x98, 0x4a, 0xfd, 0x41, 0x5d, 0x49, 0x51, 0x70, 0x55, 0x21, 0x76, 0xd1, 0x85, 0x50, 0x92, 0xe6,
	0x26, 0x2d, 0x6d, 0x7e, 0x9a, 0x99, 0x48, 0xbb, 0xeb, 0xd2, 0xa5, 0x8f, 0xe0, 0x23, 0xf8, 0x18,
	0xba, 0x73, 0xe9, 0x52, 0x93, 0x17, 0x70, 0xe9, 0x52, 0x66, 0xd2, 0x94, 0x16, 0xfd, 0xa0, 0xab,
	0x99, 0x7b, 0xee, 0x39, 0xf7, 0x9e, 0x7b, 0xf0, 0x2d, 0x0e, 0x8c, 0x4f, 0xd9, 0x6c, 0x0e, 0x91,
	0x3b, 0xdd, 0x6c, 0x36, 0x76, 0x9a, 0x25, 0x3c, 0x21, 0xba, 0x78, 0x60, 0x11, 0x9b, 0x9d, 0x30,
	0x49, 0xc2, 0x15, 0xf4, 0x25, 0xec, 0xe5, 0x41, 0x9f, 0x2f, 0x22, 0x60, 0xdc, 0x8d, 0xd2, 0x8a,
	0x69, 0xde, 0x3d, 0x74, 0xc2, 0x24, 0x4c, 0x64, 0x21, 0x7f, 0x55, 0xbb, 0xfb, 0x12, 0x93, 0xb7,
	0x7c, 0x0e, 0xd9, 0x18, 0x18, 0x7f, 0x27, 0xb7, 0x4c, 0x26, 0x13, 0x72, 0x1f, 0xab, 0x9c, 0x19,
	0x8a, 0xa5, 0xf4, 0x5a, 0x03, 0xd3, 0xae, 0x56, 0xd8, 0xf5, 0x20, 0x7b, 0x5c, 0xaf, 0x70, 0x54,
	0xce, 0xba, 0xdf, 0x34, 0x7c, 0xfd, 0x54, 0x7d, 0x03, 0x6b, 0xf9, 0xc2, 0x97, 0xf2, 0xa6, 0x23,
	0xbe, 0xe4, 0x36, 0xd6, 0x83, 0xf5, 0x34, 0x76, 0x23, 0x30, 0x54, 0x89, 0x36, 0x82, 0xf5, 0xc8,
	0x8d, 0x80, 0x3c, 0xc6, 0x17, 0x3e, 0xa4, 0xcc, 0xb8, 0xb0, 0xb4, 0x5e, 0x6b, 0x60, 0xd9, 0xfb,
	0xb3, 0xec, 0x93, 0x81, 0xf6, 0x2b, 0x48, 0xd9, 0xeb, 0x98, 0x67, 0x5b, 0x47, 0xb2, 0x09, 0xc1,
	0x1a, 0xe3, 0x99, 0x41, 0xc5, 0xa8, 0x37, 0xc8, 0x11, 0x85, 0xc0, 0xbc, 0x3c, 0x30, 0x3a, 0x96,
	0xd2, 0x6b, 0x0b, 0xcc, 0xcb, 0x83, 0xfd, 0x19, 0xfa, 0x39, 0x67, 0x90, 0x07, 0x58, 0x4b, 0x38,
	0x33, 0x9a, 0x92, 0x7c, 0xe7, 0x60, 0xe4, 0xdf, 0x70, 0x1c, 0xc1, 0x23, 0x4f, 0xb0, 0x16, 0x33,
	0x66, 0x5c, 0x93, 0xbe, 0xef, 0x5d, 0xe1, 0x7b, 0x04, 0x8c, 0x83, 0x5f, 0xd5, 0x8e, 0xe0, 0x9b,
	0x4f, 0x71, 0xfb, 0x18, 0x14, 0x51, 0x2d, 0x61, 0x5b, 0x47, 0xb5, 0x84, 0x2d, 0xb9, 0x89, 0x2f,
	0x3f, 0xb8, 0xab, 0xbc, 0x0e, 0xaa, 0x2a, 0xcc, 0xf7, 0xb8, 0x79, 0x08, 0xe1, 0x3f, 0xa2, 0xe7,
	0xc7, 0xa2, 0x33, 0xfd, 0x54, 0x8a, 0x17, 0xea, 0x33, 0x65, 0xa8, 0xe3, 0x4b, 0x1f, 0xd8, 0x2c,
	0x1b, 0x3e, 0xfc, 0xfd, 0x8b, 0x2a, 0xbb, 0x82, 0xa2, 0x8f, 0x05, 0x45, 0x5f, 0x0b, 0x8a, 0xbe,
	0x17, 0x14, 0xfd, 0x28, 0x28, 0xfa, 0x59, 0x50, 0xf4, 0xa7, 0xa0, 0x68, 0x57, 0x52, 0xf4, 0xa9,
	0xa4, 0xe8, 0x73, 0x49, 0xd1, 0x97, 0x92, 0x2a, 0x5e, 0x43, 0xc6, 0xf9, 0xe8, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x26, 0x31, 0xcf, 0x4f, 0xa8, 0x02, 0x00, 0x00,
}
