// Code generated by protoc-gen-gogo.
// source: protobuf_payload.proto
// DO NOT EDIT!

/*
Package schemas is a generated protocol buffer package.

It is generated from these files:
	protobuf_payload.proto
	protobuf_schema.proto

It has these top-level messages:
	ProtobufPayload
	ProtobufSchema
*/
package schemas

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// ProtobufPayload is a versioned protobuf payload.
type ProtobufPayload struct {
	// UID is the unique, deterministic & versioned identifier for this schema.
	UID string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Payload is the actual, marshaled protobuf payload.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ProtobufPayload) Reset()                    { *m = ProtobufPayload{} }
func (m *ProtobufPayload) String() string            { return proto.CompactTextString(m) }
func (*ProtobufPayload) ProtoMessage()               {}
func (*ProtobufPayload) Descriptor() ([]byte, []int) { return fileDescriptorProtobufPayload, []int{0} }

func (m *ProtobufPayload) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *ProtobufPayload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtobufPayload)(nil), "schemas.ProtobufPayload")
}
func (this *ProtobufPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&schemas.ProtobufPayload{")
	s = append(s, "UID: "+fmt.Sprintf("%#v", this.UID)+",\n")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringProtobufPayload(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

func init() { proto.RegisterFile("protobuf_payload.proto", fileDescriptorProtobufPayload) }

var fileDescriptorProtobufPayload = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x8b, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0xd1, 0x03, 0x0b, 0x08,
	0xb1, 0x17, 0x27, 0x67, 0xa4, 0xe6, 0x26, 0x16, 0x4b, 0xc9, 0xc2, 0x14, 0xe8, 0xa7, 0xe7, 0xa7,
	0xe7, 0x83, 0x39, 0x60, 0x16, 0x44, 0x9d, 0x52, 0x30, 0x17, 0x7f, 0x00, 0x54, 0x41, 0x00, 0xc4,
	0x00, 0x21, 0x49, 0x2e, 0xe6, 0xd2, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x4e, 0x27, 0xf6,
	0x47, 0xf7, 0xe4, 0x99, 0x43, 0x3d, 0x5d, 0x82, 0x40, 0x62, 0x42, 0xaa, 0x5c, 0xec, 0x50, 0x6b,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x9c, 0xb8, 0x1f, 0xdd, 0x93, 0x67, 0x87, 0x6a, 0x0c, 0x82,
	0xc9, 0x39, 0x19, 0x7c, 0x78, 0x28, 0xc7, 0xd8, 0xf0, 0x48, 0x8e, 0xa1, 0xe3, 0x91, 0x1c, 0xc3,
	0x89, 0x47, 0x72, 0x0c, 0x17, 0x1e, 0xc9, 0x31, 0xdc, 0x78, 0x24, 0xc7, 0xf0, 0xe0, 0x91, 0x1c,
	0xc3, 0x8f, 0x47, 0x72, 0x0c, 0x0d, 0x8f, 0xe5, 0x18, 0x26, 0x3c, 0x96, 0x63, 0x58, 0xf0, 0x58,
	0x8e, 0x61, 0xc3, 0x63, 0x39, 0xc6, 0x24, 0x36, 0xb0, 0x6b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x86, 0xa1, 0x57, 0xcf, 0x00, 0x00, 0x00,
}
