// Code generated by "linkname-gen -symbol github.com/gogo/protobuf/proto.(*Buffer).unmarshalType -def func unmarshalType(*proto.Buffer, reflect.Type, *proto.StructProperties, bool, unsafe.Pointer) error"; DO NOT EDIT.

package wirer

import (
	"reflect"
	"unsafe"
	_ "unsafe"

	"github.com/gogo/protobuf/proto"
)

//go:linkname unmarshalType github.com/gogo/protobuf/proto.(*Buffer).unmarshalType
func unmarshalType(*proto.Buffer, reflect.Type, *proto.StructProperties, bool, unsafe.Pointer) error
